### ISSUE TITLE
V. 0.8.3 not applying 'caption' options from YAML header?

### ISSUE THREAD

**Issue by mike-levine** [davidgohel/flextable#496]
I've been using flextable `v 0.7.3`, and the YAML header options under `caption` render to a Word document as requested (specifically, the settings to `pre:` and `sep:`). Using  `v 0.7.3`, this Rmarkdown code produces a word document with the expected output, i.e. a table with the caption: *A TABLE! 1. -- This is a caption*

```
---
output: 
  officedown::rdocx_document:
    tables:
      style: Table
      layout: autofit
      width: 1.0
      topcaption: true
      tab.lp: 'tab:'
      caption:
        style: Table Caption
        pre: 'A TABLE! '
        sep: '. -- '
        fp_text: !expr officer::fp_text_lite(bold = FALSE)
      conditional:
        first_row: true
        first_column: false
        last_row: false
        last_column: false
        no_hband: false
        no_vband: true
    plots:
      style: Normal
      align: center
      caption:
        style: Image Caption
        pre: 'Figure '
        sep: ': '
    lists:
      ol.style: null
      ul.style: null
---
```
```{r setup, include=FALSE}

library(officedown)
library(flextable)

```

```{r table, echo = FALSE, results='asis'}

#get a flextable and a caption
ft = flextable::flextable(head(iris))
cap = 'This is a caption'

#set the caption
print_table = set_caption(ft, 
                          caption = cap, 
                          style = "Table Caption")

flextable_to_rmd(x = print_table, ft.align = 'center', ft.split = FALSE, ft.keepnext = FALSE, print = TRUE)

```

With `v 0.7.3`, my output is:
![image](https://user-images.githubusercontent.com/17622900/211916088-31750cfe-fa7f-4b3b-bf70-b76a536752f1.png)
Updating package to `v 0.8.3` and running the same code results in this output:
![image](https://user-images.githubusercontent.com/17622900/211916237-13bf43ff-1146-4435-b075-e3d55704b054.png)

Is this behavior intended? Do I need to be specifying captions differently with `v 0.8.3`? 

Thanks for the great package(s)- flextable/officedown/officer are very useful in our work!
